package gg.paceman.aatracker.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.apache.commons.lang3.tuple.Pair;

import javax.swing.*;
import java.awt.*;

public class AATrackerPanel {
    private JPanel mainPanel;
    private JPanel trackerPanel;
    private AATrackerGUI gui;

    public static Pair<AATrackerGUI, JPanel> getNewGUIAsPanel() {
        AATrackerPanel aaTrackerPanel = new AATrackerPanel();
        return Pair.of(aaTrackerPanel.gui, aaTrackerPanel.trackerPanel);
    }

    private void createUIComponents() {
        this.gui = AATrackerGUI.getHeadless();
        this.trackerPanel = this.gui.getMainPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(trackerPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
